### ISSUE TITLE
tests not working for most of the labs in the React section

### ISSUE THREAD

**Issue by ndaniele** [learn-co-curriculum/javascript-objects-lab#8]
I can't seem to get any of the tests to run correctly in this React Section. 

Everytime I run 

$ Learn 

in my terminal i get the same response: 

  1)  "before each" hook for "defines a `recipes` object":
     Error: timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.
      at Object.done (node_modules/mocha-jsdom/index.js:70:7)
      at process.nextTick (node_modules/jsdom/lib/jsdom.js:320:18)
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickCallback (internal/process/next_tick.js:98:9)

So, not sure what to do about this. It seems like maybe the tests aren't fully built out for this section yet, because even though I get these errors I still get the "local tests passing" light to light up. ..not sure what's going on here.

**Comment by bhollan** [comment]
You could try extending the `timeout` value.  In `package.json` you can alter the `test` script.
```
"scripts": {
  "test": "mocha --timeout 15000 -R mocha-multi --reporter-options nyan=-,json=.results.json"
},
```

**Comment by aturkewi** [comment]
I don't think this is an issue with the lab, but rather an issue with your local setup. @ndaniele was @bhollan solution helpful?

I'm going to close this issue on here for now, but ping me if you still need a hand!

**Comment by ndaniele** [comment]
very helpful! thank you all!
